version: "2"
services:
  chromebrowser:
    image: selenium/standalone-chrome:3.12.0-cobalt
    ports:
      - "4444:4444"
    networks:
      - watchrunet
    restart: always
    shm_size: 512M
    #volumes:
      #- /dev/shm:/dev/shm
  watchruscrapper:
    build:
      context: .
      dockerfile: Dockerfile_scrapper
    volumes:
      - /data_watch_ru:/WatchRuMonitoring_bot/data
    restart: always
    networks:
      - watchrunet
  watchrubot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    volumes:
      - /data_watch_ru:/WatchRuMonitoring_bot/data
    restart: always
    networks:
      - watchrunet

networks:
  watchrunet: